export interface IKontodata {
  frie_uttak?: number;
  grensebelop1?: number;
  grensebelop2?: number | string;
  grensebelop3?: number | string;
  grensebelop4?: number | string;
  grensebelop5?: number | string;
  grensebelop6?: number | string;
  gruppe?: string;
  highestEntryFee?: number;
  highestEntryFeeRequirements?: string;
  kap_periode?: number;
  leverandor?: string;
  leverandor_tekst?: string;
  lowestEntryFee?: number;
  lowestEntryFeeRequirements?: string;
  maks_alder?: number;
  maks_belop?: number;
  manedlig_sparing?: boolean;
  manedlig_sparing_maks_belop?: string;
  manedlig_sparing_min_belop?: string;
  markedsomraade?: string;
  markedsomraadeBoliglan?: string;
  markedsomraadeBoliglanTekst?: string;
  markedsomraadeTekst?: string;
  medlemskap?: string;
  medlemskap_tekst?: string;
  min_alder?: number;
  min_belop?: number;
  navn?: string;
  oppfolging?: boolean;
  pensjonist?: boolean;
  produktpakke?: string;
  produktpakke_tekst?: string;
  publiserFra?: string;
  publiserTil?: string;
  rentesats1?: number;
  rentesats2?: string;
  rentesats3?: string;
  rentesats4?: string;
  rentesats5?: string;
  rentesats6?: string;
  spesielle_betingelser?: string;
  student?: boolean;
  trapp_type?: string;
  trenger_ikke_pakke?: boolean;
  id?: string;
  link?: string;
  title?: string;
}
